# Generated by Django 6.0.6 on 2026-06-25 11:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='workerprofile',
            old_name='document_url',
            new_name='bio',
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='current_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='service_radius',
            field=models.PositiveIntegerField(default=10, help_text='Radius in KM'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='status',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('BUSY', 'Busy')], default='OFFLINE', max_length=10),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='verification_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='total_jobs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='workerprofile',
            index=models.Index(fields=['status'], name='accounts_wo_status_005fd2_idx'),
        ),
        migrations.AddIndex(
            model_name='workerprofile',
            index=models.Index(fields=['is_verified'], name='accounts_wo_is_veri_04d38d_idx'),
        ),
        migrations.AddIndex(
            model_name='workerprofile',
            index=models.Index(fields=['is_available'], name='accounts_wo_is_avai_5f04e8_idx'),
        ),
    ]
