# Generated by Django 6.0.6 on 2026-06-28 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_and_more'),
        ('services', '0004_servicerequest_assigned_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='services.servicecategory'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='workerprofile',
            index=models.Index(fields=['category'], name='accounts_wo_categor_d92470_idx'),
        ),
    ]
