# Generated by Django 6.0.6 on 2026-07-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_workerprofile_category_workerprofile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='aadhaar_number',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
