# Generated by Django 6.0.6 on 2026-06-25 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_and_more'),
        ('services', '0002_servicerequest_requestimage_and_more'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerskill',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workerskill',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workerskill',
            name='skill_level',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('EXPERT', 'Expert')], default='INTERMEDIATE', max_length=20),
        ),
        migrations.AlterField(
            model_name='workerskill',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_skills', to='services.servicecategory'),
        ),
        migrations.AlterUniqueTogether(
            name='workerskill',
            unique_together={('worker', 'category')},
        ),
    ]
