# Generated by Django 6.0.6 on 2026-06-25 12:45

import django.db.models.deletion
import tracking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_and_more'),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerassignment',
            name='completion_otp',
            field=models.CharField(default=tracking.models.generate_otp, max_length=6),
        ),
        migrations.AlterField(
            model_name='workerassignment',
            name='start_otp',
            field=models.CharField(default=tracking.models.generate_otp, max_length=6),
        ),
        migrations.CreateModel(
            name='WorkerLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('speed', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('heading', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='accounts.workerprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['worker'], name='tracking_wo_worker__638982_idx')],
            },
        ),
    ]
