# Generated by Django 6.0.6 on 2026-06-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicerequest_requestimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='icon',
            field=models.CharField(default='tools', max_length=50),
        ),
    ]
