# Generated by Django 6.0.6 on 2026-06-27 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_and_more'),
        ('services', '0003_servicecategory_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='assigned_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to='accounts.workerprofile'),
        ),
    ]
